### ISSUE TITLE
[CommonsChunkPlugin] add some examples link

### ISSUE THREAD

**Issue by wuxiandiejia** [webpack/webpack.js.org#1018]
Could add https://github.com/webpack/webpack/tree/master/examples/move-to-parent 
and  https://github.com/webpack/webpack/tree/master/examples/extra-async-chunk 
to the [CommonsChunkPlugin page](https://webpack.js.org/plugins/commons-chunk-plugin/).
Because I think the `children` and `async` option is not easy to understand without a example.

**Comment by rouzbeh84** [comment]
Made some recent PR's to add other documentation to [plugins](https://webpack.js.org/plugins) myself due to this but thought [commons-chunk-plugin](https://webpack.js.org/plugins/commons-chunk-plugin/) was quite thorough. 

It includes [async](https://webpack.js.org/plugins/commons-chunk-plugin/#extra-async-commons-chunk) and [move-to-parent](https://webpack.js.org/plugins/commons-chunk-plugin/#move-common-modules-into-the-parent-chunk) info. Is there anything in particular you have a question on? 

The [file itself](https://github.com/webpack/webpack/blob/master/lib/optimize/CommonsChunkPlugin.js) has some great comments throughout too :)

**Comment by wuxiandiejia** [comment]
@rouzbeh84 I don't know what's the `children` mean,can you give a example?

**Comment by skipjack** [comment]
@wuxiandiejia `children` means child bundles/chunks created using [on demand code splitting](https://webpack.js.org/guides/code-splitting/#on-demand-code-splitting). Basically the `children` key tells the plugin to find common dependencies between the children and move them up to a parent bundle so they aren't duplicated.

**Comment by wuxiandiejia** [comment]
@skipjack Thank you.I didn't notice the code splitting in the section. Can you add the link of it to highlight it?

**Comment by rouzbeh84** [comment]
here you go [parents/children](https://webpack.js.org/plugins/commons-chunk-plugin/#move-common-modules-into-the-parent-chunk) and the [file itself](https://github.com/webpack/webpack/blob/master/lib/optimize/CommonsChunkPlugin.js) may help as would maybe the [code example](https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks)

**Comment by wuxiandiejia** [comment]
@rouzbeh84 Thank you. I will see them.
