### ISSUE TITLE
npm run test  => error

### ISSUE THREAD

**Issue by Aladdin-ADD** [webpack/webpack.js.org#1041]
after `npm install`, `npm run build`, `npm run test`, I  got some eslint errors:
![image](https://cloud.githubusercontent.com/assets/13050025/24145161/ea14ee2e-0e6a-11e7-9aa1-af71acb86038.png)

Did I forget something?

**Comment by skipjack** [comment]
@Aladdin-ADD good point, I believe the issue is that we're using our same eslint configuration for the markdown javascript samples as we are for the actual code running the site. There's definitely value in this but if we want to continue this process it's probably worth defining some separate, more lax, rules for the javascript within `.md` files.

@webpack/documentation-team any thoughts? I forget who set this up initially...

**Comment by bebraw** [comment]
Yeah, most likely we want separate linting setups per site/content to fix this.

**Comment by skipjack** [comment]
Tackling this now.
