### ISSUE TITLE
How to - Shim

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#13]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/how-to/shim.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by SpaceK33z** [comment]
We could use the content of @jhnns's blog post about [how to cope with broken modules here](https://medium.com/webpack/how-to-cope-with-broken-modules-in-webpack-4c0427fb23a) (this was suggested on Slack).

**Comment by pksjce** [comment]
@SpaceK33z - I will pick this up. Thats a great article!

**Comment by wearhere** [comment]
That article appears to be a good resource for shimming browser globals (tip 2) and module systems (tips 3 and 4). I would love to also see documentation for shimming Node globals/built-ins—I think that's one of the most magical parts of Webpack (in a not-entirely good way) insofar as it happens without the developer telling Webpack to do so. See #153.

Excerpted from that issue, some topics to cover in this guide would be (my stabs at documentation following the colons):
* how shimming Node built-ins/globals is triggered: you `require` a Node built-in or use a Node global anywhere in your input to Webpack
* what modules/globals are shimmed: so far I have seen `os`, `crypto`, and `Buffer`
* how to disable this shimming: define the module as an [external](https://webpack.github.io/docs/library-and-externals.html) or use `DefinePlugin` to wrap the `require` in a [dead branch](https://github.com/webpack/webpack/issues/99#issuecomment-24985486)
* where should bugs against the shims be filed—is Webpack responsible for them per se?

I also think that Webpack should suggest that developers use browser APIs where available rather than relying on the shims. For instance, [`SubtleCrypto`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) is almost equivalent to `crypto`, the former's use of promises aside. Developers can save 100kB of JS, and worry less about correctness, by using the browser's API vs. a 3rd-party implementation.

**Comment by bebraw** [comment]
Please take a note of https://github.com/webpack/webpack.js.org/issues/63#issuecomment-237858705 . That's fitting info for this article.

**Comment by pksjce** [comment]
Will be sure to include it.

**Comment by jrvidal** [comment]
Did  7950c8f tackle the original request in https://github.com/webpack/webpack.js.org/issues/153 / https://github.com/webpack/webpack/issues/2871?

**Comment by bebraw** [comment]
@jrvidal Thanks for the heads up. Looks like we missed the Node bits on the first pass.

**Comment by pksjce** [comment]
@jrvidal - I did not have a full understanding of the node shims you mentioned above. Maybe you could add to what's done already?
