### ISSUE TITLE
Dev - Tooltip Issue in Backers Section

### ISSUE THREAD

**Issue by dhilt** [webpack/webpack.js.org#1360]
Something's not ok with Angular in the Backers section...

![_zero](https://user-images.githubusercontent.com/4365660/27772326-84c05190-5f68-11e7-8744-2dc604b5abd6.png)

**Comment by d3viant0ne** [comment]
Check the sponsors section, I'm betting it has to do with multiple users. Note the `Google Angular` in the sponsor section vs. `Angular` in the backers section.

**Comment by skipjack** [comment]
Weird it seems all their `donation` amounts are coming in `null` from OpenCollective when we pull the JSON... this may be an issue with their account or on OpenCollective's end.

![image](https://user-images.githubusercontent.com/8988697/27772868-ca25e22a-5f38-11e7-9f38-e5c776588ad4.png)

**Comment by skipjack** [comment]
If anyone else wants to debug, the code can be found [here](https://github.com/webpack/webpack.js.org/tree/master/components/support). You'll have to stand up the site locally though as the OpenCollective JSON is pulled into that directory dynamically.

As mentioned above, I don't think this issue is on our side -- although `null` values should cause the backer to be sorted to the bottom of the list.

**Comment by skipjack** [comment]
Let's track on opencollective/opencollective#364 for now as I believe there is some issue with that account on their end. If it does turn out to be something on ours I'm happy to re-open this and address it.
