### ISSUE TITLE
Guides - question on Output Filenames under Caching

### ISSUE THREAD

**Issue by sudarsangp** [webpack/webpack.js.org#1496]
**Under Output Filenames section in Caching**

Following the docs, when I run the command (multiple times) `npm run build` there is no change in the filename.
`main.c396e62535527ae6a15a.js`

The docs state that:
 _If we run another build without making any changes, we'd expect that filename to stay the same. However, upon running it, we'll see that this is not the case. This is because webpack includes certain boilerplate, specifically the runtime and manifest, in the entry chunk_

Version: webpack 3.4.1

Maybe I am missing something here?

**Comment by skipjack** [comment]
I think you may be correct, I saw some inconsistencies as well when testing different versions. I'd like to leave it as is for now, just in case because the extraction and extra plugins shouldn't hurt anything (and most of the extraction is best practice anyway).

I'm closing but if you wanted to add a small note/warning to that page just mentioning that output may differ depending on the version, e.g.

```md
W> Output may differ depending on your current webpack version. Newer versions may not have all the same issues with hashing as some older versions, but we still recommend the following steps to be safe.
```

or something like that, we would gladly accept the PR!

**Comment by skipjack** [comment]
Just re-read that section of the guide -- I don't think you're doing anything wrong, I think it's that other changes that shouldn't change the hash still might (even on the latest version).
