### ISSUE TITLE
Guides - Migrating from v2 to v3

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack.js.org#1569]
![image](https://user-images.githubusercontent.com/1060733/30010772-dc76286e-9164-11e7-8784-40f6e618c439.png)

there is a section for migrating from v1 to v2, but how about from v2 to v3?

**Comment by zzzgit** [comment]
i want to update webpack in my project from 2 to 3,but i can not do this hastily without a instruction

**Comment by skipjack** [comment]
@zzzgit currently we only have the document for migrating from v1 to v2. This is because there were a lot more breaking changes from v1 to v2 than from v2 to v3. In fact, I migrated a bunch of projects to v3 without having to _make any major configuration changes_.

I would recommend just reviewing [release notes](https://github.com/webpack/webpack/releases/tag/v3.0.0) for v3 and see if there's anything flagged `[breaking change]` that would affect your setup.

We do have a note in the current guide to note this:

![image](https://user-images.githubusercontent.com/8988697/30087346-2bc1ef98-926e-11e7-84a6-ed1e59f97781.png)

I agree that this is slightly confusing and, long term, I think we should resolve this in one of two ways:

- Remove the _Migrating from v1 to v2_ guide and push these articles to blog posts instead as they become dated very quickly with new releases. We could even add a redirect to the blog post for the removed guide.
- Rename this guide _Migrating Versions_ and include notes on the breaking changes for each major release.

Frankly, I would lean towards the first option (and continue to improve on release notes) as it's been hard enough just to maintain our core guides/content. I'm going to close for now as we do already have a note in that guide but I'm marking with a `reconsider` label so we can revisit it later on. Our main goal right now is to continue cleaning up and restructuring the existing content (e.g. #1258 and others) and fixing some dev/infrastructure issues (#1525 and #1400).
