### ISSUE TITLE
Docs - eval-cheap-module- vs. cheap-module-eval-

### ISSUE THREAD

**Issue by marcofugaro** [webpack/webpack.js.org#1577]
In some parts it's `eval-cheap-module-source-map`,
https://webpack.js.org/api/cli/#shortcuts
https://webpack.js.org/guides/build-performance/#devtool

Instead in the Sourcemap documentation it's `cheap-module-eval-source-map`:

https://webpack.js.org/configuration/devtool/

Which one is correct? Searching for those in the webpack repo, it gives results for both of the words.

**Comment by skipjack** [comment]
@marcofugaro thank you for highlighting this. I believe the `devtool` configuration docs are correct and it's `cheap-module-eval-source-map`. @sokra updated these recently, @sokra can you confirm? I'm happy to pick this up if no one else does.

**Comment by sokra** [comment]
You can use whatever you like most, as long `str.contains("eval") === true`.

https://github.com/webpack/webpack/blob/92d5c209437f9ef9293571e24cc8dcf10459d578/lib/WebpackOptionsApply.js#L201-L205

**Comment by skipjack** [comment]
Ah interesting... ok I'll update the other instances for consistency. @sokra `devtool` does seem like an option that might benefit from being fleshed out into an object some day. I think it's a bit more intuitive to understand something like:

``` js
{
  type: 'normal',
  cheap: true,
  eval: true, 
  module: true 
}
```

and then document them each as separate options rather than full strings. One downside to this though is that it would make passing it via the CLI a bit harder.

**Comment by marcofugaro** [comment]
Good job @skipjack!

Are you sure the `-d` option sets the devtool to `cheap-module-source-map` and not `cheap-module-eval-source-map` like it was before? Was the documentation wrong before?

**Comment by skipjack** [comment]
@marcofugaro good catch, that was unintentional... I'll resolve shortly.
