### ISSUE TITLE
Guides - HashedModuleIdsPlugin in Caching

### ISSUE THREAD

**Issue by danny-andrews** [webpack/webpack.js.org#1597]
Turns out using `NamedModulesPlugin` leads to smaller bundle sizes after gzipping (crazy, right!?)

My calculations suggest a savings of 9%! https://docs.google.com/spreadsheets/d/19X7YZ9ULdB1INpTAL0IHAAoMrQ1Vit219IH1iisBfMo/edit?usp=sharing

This was brought to my attention [here](https://medium.com/@mikegreiling/shouldnt-we-prefer-to-use-hashedmoduleidsplugin-over-namedmodulesplugin-in-production-c01329cf787a).

**Comment by skipjack** [comment]
> Quit recommending HashedModuleIdsPlugin for production

Woah, you make it sound like were recommending it everywhere!! It's only mentioned in one guide (besides that plugin's documentation):

![image](https://user-images.githubusercontent.com/8988697/30507401-3e9ef534-9a52-11e7-9dad-30409f524948.png)

This was intentional by the way as using the `HashedModuleIdsPlugin` is simpler and requires less overhead than including both the `NamedModulesPlugin` and `NamedChunksPlugin`. There is a balance to be found between super optimized configs and something the general audience can easily understand.

_That said...._ a 9% gain is significant and I did read the similar discussions on @timse's article. I see two routes to resolve this:

- Add a tip (`T>`) at the end of the [Module Identifiers][1] section pointing to @timse's article highlighting the fact bundle sizes may be decreased using the `NamedModulesPlugin` and `NamedChunksPlugin`.
- Refactor the whole [section][1] to recommend those in the first place. If we go this route, we need to make sure to test the changes [here][2].

Frankly I'd lean towards the first as we have a lot of other high priority infrastructure and review work to do on the site. However, if you have the time to carefully tackle revising the guide, we'd be happy to accept a pull request with this change.

[1]: https://webpack.js.org/guides/caching/#module-identifiers
[2]: https://github.com/TheDutchCoder/webpack-guides-code-examples/tree/master/examples/caching

**Comment by danny-andrews** [comment]
@skipjack Thanks for the quick and detailed reply! My original issue title may have come off a bit blunt. Sorry about that. I usually try to make them as direct as possible and then explain more in the body of the issue.

I actually didn't know that `HashedModuleIdsPlugin` eliminated the need for `NamedModulesPlugin` and `NamedChunksPlugin`. That's pretty neat! However, you'd still have to know to use those two plugins in development. I actually believe this is a symptom of the long-term caching story in webpack still being pretty convoluted (see this 2-year-old issue which is very much alive): https://github.com/webpack/webpack/issues/1315#issuecomment-329897948. But that's not simply a documentation issue.

I also noticed that there's already a link to his his article at the end of the caching guide. I think this issue would be better suited to the webpack repo proper, as it will require some code changes. Sorry for the noise and thanks again for the info!

**Comment by skipjack** [comment]
> Thanks for the quick and detailed reply! My original issue title may have come off a bit blunt. Sorry about that. I usually try to make them as direct as possible and then explain more in the body of the issue.

No worries at all, I found the title more funny than offensive.

> However, you'd still have to know to use those two plugins in development. I actually believe this is a symptom of the long-term caching story in webpack still being pretty convoluted...
> I also noticed that there's already a link to his his article at the end of the caching guide. I think this issue would be better suited to the webpack repo proper, as it will require some code changes. Sorry for the noise and thanks again for the info!

Didn't mean to shut down your issue btw, it's just that we've been making a lot of progress cleaning up and structuring the existing content so I want to keep going on that front. Obviously if documentation is missing it is what it is and it'll have to be dealt with, but for smaller optimizations I think it's worthwhile keeping things simple for now and elaborating on them later. 

I do think the @webpack/core-team has caching/hashing in mind as something that could be simplified and I also think there have already been some improvements in that process with the version 2 and 3 releases. You make a good point re the development setup needing those plugins -- feel free to check back in with us in a few months and we can consider revising some of those guides (or feel free to submit a PR sooner). Hopefully the repo/site will be in a cleaner state by then.

**Comment by danny-andrews** [comment]
> Didn't mean to shut down your issue btw

Not at all. You comments made me realize the path I was suggesting would make setting up long-term caching *more* convoluted, not less. et. al:

> for smaller optimizations I think it's ok to keep things simple for now and elaborate on them later.

I'll be tracking progress on this ticket: https://github.com/webpack/webpack/issues/4913#issuecomment-330103772.

Cheers!
