### ISSUE TITLE
Guides - `Enabling Tree-shaking` Missing from TypeScript

### ISSUE THREAD

**Issue by ohze** [webpack/webpack.js.org#1627]
[Enabling Tree-shaking](https://github.com/webpack/webpack.js.org/blob/de7e5ffb2938a1edcc9a0e9fe3b370d7b97f7d6a/content/guides/webpack-and-typescript.md#enabling-tree-shaking) section not found ([in this tree](https://github.com/webpack/webpack.js.org/tree/99bf48d4a6)) after commit 99bf48d4a6

**Comment by skipjack** [comment]
Thanks for bringing this up. I don't think that whole section needs needs to be added back but the example `tsconfig.json` should be use `es6` instead for the following options:

``` js
"target": "es6",
"module": "es6",
```

Would you be willing to submit a PR?

**Comment by skipjack** [comment]
And actually maybe just the second of those two things -- i.e. `"module": "es6"`. To enable tree-shaking you simply have to allow it to process `import` / `export` statements on its own (instead of having Babel or another transpiler handle them) and include the `UglifyJSPlugin`. The _Tree Shaking_ guide has more details but I think we should keep the _TypeScript_ guide as simple as possible.

**Comment by dmitriid** [comment]
Just checked, this is correct. You only need `module: es6`

**Comment by skipjack** [comment]
@dmitriid awesome, thank you. I will PR the change this weekend if no one beats me to it.
