### ISSUE TITLE
API - Delineate and Elaborate on Dynamic Expressions

### ISSUE THREAD

**Issue by stereokai** [webpack/webpack.js.org#1699]
I searched and searched but couldn't find any mention of this feature in the new website.

https://webpack.github.io/docs/context.html

It speaks of *dynamic imports*:
```js
require("./template/" + name + ".jade");
```

So I was wondering first of all - is that on purpose? ie. is this feature deprecated? If not, and if it really isn't in the docs, then I can start a PR for updating the docs with this useful information.

**Comment by skipjack** [comment]
So I searched "dynamic imports" and results do pop up for the _Code Splitting_ guide:

![image](https://user-images.githubusercontent.com/8988697/32755859-3807911e-c8a5-11e7-853f-79ea3d3032ae.png)

Which is one useful place to look. That guide also links to the [Module Methods](https://webpack.js.org/api/module-methods/#import-) which contains even more detail on dynamic imports.

To answer your question though, the feature _definitely still exists_, but is typically accessed via the ES6+ `import()` method which webpack now supports out of the box. I believe dynamic `require`s are still supported as well, so if you wanted to submit a PR that adds a small `T> ...` (custom tip syntax) that notes this in the [`require` section](https://webpack.js.org/api/module-methods/#require) and links to the `import()` section, I would gladly review and accept it!

For example:

``` md
T> Dynamic imports using `require` are supported as well and follow the same rules as those specified for [`import()`](...).
```

**Comment by stereokai** [comment]
@skipjack Have you looked inside that "Dynamic Imports" page? It's talking about code-splitting. I.e., "dynamically importing a chunk", not expressions in the `require` or `import` calls. 

This in and of itself points to a broader problem in the webpack world, that there are 2 features with the same name. One dynamic imports is means splitting the codebase and loading a chunk on-demand during runtime, and the other dynamic imports means deciding which modules to tell webpack to parse.

So no, this feature is not covered in the docs. At least not as in depth as in the Webpack 1 docs, because I did find an ["honorary mention"](https://webpack.js.org/guides/migrating/#dynamic-expressions) in the migration guide.

**Comment by skipjack** [comment]
Fair points.

> Have you looked inside that "Dynamic Imports" page? It's talking about code-splitting. I.e., "dynamically importing a chunk", not expressions in the require or import calls.

You're right, I am familiar with that page but only skimmed it yesterday when answering to see if it contained a link to the [`import()` docs](https://webpack.js.org/api/module-methods/#import-).

> This in and of itself points to a broader problem in the webpack world, that there are 2 features with the same name. One dynamic imports is means splitting the codebase and loading a chunk on-demand during runtime, and the other dynamic imports means deciding which modules to tell webpack to parse.

Dynamic importing, not only in webpack but in the community as far as I've seen, commonly refers to three things actually:

- Loading a module and its dependencies at runtime (_Lazy Loading_) based on some logic.
- _Code Splitting_ is required for the above otherwise nothing would be there to load.
- _Dynamic Expressions_, also available only when some calculation/logic happens at run time.

So I do think _Dynamic Imports_ is the umbrella for all three topics. However, while the other two are clearly expressed in the docs, _Dynamic Expressions_ isn't as well defined or delineated.

After looking through the [`import()` docs](https://webpack.js.org/api/module-methods/#import-) again this morning, I realize the only discussion _Dynamic Expressions_ is in these two warnings:

![image](https://user-images.githubusercontent.com/8988697/32782219-c21be36c-c915-11e7-832e-4c3c5035838d.png)

So, to your point, there is probably a somewhat longer list of action items:

- [ ] Expand the two warnings into one or two more thorough paragraphs under `import()`.
- [ ] Test dynamic expressions with `require` to see if they still work, and if so, mention them in the `require()` section.
- [ ] Potentially mention _Dynamic Expressions_ in the [Code Splitting](https://webpack.js.org/guides/code-splitting/) guide. Not sure a full diff is needed but at least another link to `import()` for further reading would be useful.
- [ ] Throughout all these places, make sure the term _dynamic expressions_ is used. And anywhere _dynamic imports_ is used, make sure it is clearly the umbrella term for all three.

🙏  forgive me for brushing over this a little too quickly. If you agree those action items would resolve the problem you've brought up, then (as mentioned above) I would definitely love it if you were to submit a PR. Also, feel free to let me know if there's anything else I can do to facilitate.

**Comment by skipjack** [comment]
@stereokai are you still interested in submitting a PR?

**Comment by stereokai** [comment]
Yes, I took a few days off due to sickness. Definitely want to start working on it this week

**Comment by skipjack** [comment]
@stereokai any progress on this? Happy to help if I can...

**Comment by stereokai** [comment]
@skipjack Hey, thanks! I've been busy, but I will take care of it before the new year :)

**Comment by montogeek** [comment]
@EugeneHlushko Something we can do

**Comment by EugeneHlushko** [comment]
Hmm right, all bullets seem to make sense. Wanna pick up or should i? @montogeek

**Comment by montogeek** [comment]
@EugeneHlushko You :)

**Comment by stereokai** [comment]
I completely forgot about this, excuse me :O
