### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#17]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/changelog.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by kentcdodds** [comment]
This could be automated if the project follows a commit message convention. You could encourage contributors to follow it, but because of GitHub's squash and merge feature, you can change the commit message of people's contributions if they don't follow the convention, which means it wont be a barrier to contributing.

It's incredibly nice to be able to automate the creation of a changelog using git commit messages. You can update the changelog manually if you want after the automation has created it.

Personally, I'd say using semantic-release would be the best because it'll automate releases for you too. But if you'd prefer to not do that, then you can use [clog](https://github.com/clog-tool/clog-cli).

**Comment by bebraw** [comment]
Yup. I'm not sure if we end up maintaining a changelog at the site even. Perhaps the easiest thing to do would be to link to GitHub releases page and solve it there.

I agree automation would be good, but this is up to @sokra to figure out.

**Comment by d3viant0ne** [comment]
@bebraw - conventional-changelog + semantic-release + enforcing commit message formatting ( Committizen does this) === Automated changelog generation and versioning. 

Nothing to figure out here as the path forward is pretty standard. Angular / Material2 and a host of other major libs have already blazed this trail. 

The above is currently being implemented in karma-webpack

**Comment by TheLarkInn** [comment]
Wow I really like @d3viant0ne suggestion of Committizen. That could take a lot of leg work out of the process for some folks. Could be highly useful

**Comment by bebraw** [comment]
Let's solve this with a link to GitHub releases for the MVP.
