### ISSUE TITLE
Asset Management Demo in Docs - Images not rendering

### ISSUE THREAD

**Issue by idkjs** [webpack/webpack.js.org#1712]
I'm going through the Asset Management walkthrough and not getting the expected output. I get a broken image and no background as expected. 

This is the rendered image output in firefox.
https://screenshots.firefox.com/0AavWn4o1Y2aCOvG/null

This is [webpack.config.js gist](https://gist.github.com/idkjs/7acb4548332d3ea191e506c5e2f03685)

 This is the directory

```sh
├── dist
│   ├── 6336f9ce7a637380ba3ddb2ec76a4f95.png
│   └── bundle.js
├── index.html
├── package-lock.json
├── package.json
├── readme.md
├── src
│   ├── icon.png
│   ├── index.js
│   ├── paris.jpeg
│   └── style.css
└── webpack.config.js
```

- Package.json [gist](https://gist.github.com/idkjs/b33578f661b50b53e1019096225238d9)

**Comment by skipjack** [comment]
The issue seems to be that you specified the `.jpeg` extension on `paris.jpeg` but in your config you only handle `.jpg`s (i.e. `/\.(png|svg|jpg|gif)$/` => `/\.(png|svg|jpeg|gif)$/` or `/\.(png|svg|jpe?g|gif)$/` or just update the extension on the file. Btw, this isn't really a support channel -- stack overflow or the webpack/webpack gitter channel is a better place for these types of questions.

If the issue ends up being with the guide, please re-open with details and a full repo that reproduces the issue.

**Comment by skipjack** [comment]
The `.png` does look like it's being processed and emitted so if that's the one that's failing I'm not sure what's going on. We would need access to the full example to debug and reproduce.

**Comment by idkjs** [comment]
Figured this was a docs issue so posted here. Here is the repo which i think duplicates the docs example with 2 exceptions. The docs run build output says its using webpack 2.6.1 instead of the latest and my script ref in index.html is `./dist/bundle.js` instead of of `bundle.js`. Didnt work with bundle.js.

full test repo https://github.com/idkjs/webpack.org.js-docs-demo

**Comment by skipjack** [comment]
Try putting your `index.html` file within `/dist` as shown at the [end](https://webpack.js.org/guides/getting-started/#conclusion) of _Getting Started. Change the script `src` to `src="/bundle.js"` or `src="bundle.js"` as shown in _Getting Started_. If you use the absolute path, you should be using something like [http-server](https://www.npmjs.com/package/http-server) to serve the site instead of just opening the `index.html` in the browser.

The issue is that the output image is relative to the `bundle.js` not the `index.html` file which is why they should be in the same directory (without using a more complex configuration). I would recommend re-reading the _Getting Started_ guide to make sure you didn't miss anything else before moving on to the other guides.

**Comment by idkjs** [comment]
@skipjack thank you, sir. Somehow missed that change in [creating a bundle](https://webpack.js.org/guides/getting-started/#creating-a-bundle). I appreciate your seasoned eyes and patience. Thanks again.
