### ISSUE TITLE
Concepts - Document Language Extension

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#1736]
This is a stub for another potential contributor to document some of their existing painpoints and lack of docs for understanding how to switch from a system like gulp without modules, etc => using modules, webpack, why, and how.

**Comment by c-johnson** [comment]
The specific thing I was unclear about was that Webpack is an _extension of the Javascript language itself_, IE, a "complier", and not simply a build tool that you can swap out for other build tools like Gulp, Grunt, Browserify, etc.

Specifically, the import extensions for CSS, images, and other static assets are not part of Javascript at all. They're extra features that Webpack adds that will break your source code if you choose to replace Webpack with another "build tool".

This couples the <source code> of your application to the <build tool> by making them all one system. I think this is well-understood by seasoned Webpack developers, but was not well understood by me, a regular Javascript developer who sees "Gulp vs Webpack!" articles everywhere and thought that they were both swap-outtable for each other. (In fact, you can swap out Gulp for Webpack, but you cannot do the same in reverse if you use Webpack loaders).

The only thing I would suggest changing is making the documentation on this more clear on the main website. If developers knew that they were buying into an _alternate version of Javascript_ when they were installing Webpack, I would be happy that these rather strong trade-offs are adequately communicated.

I also understand how silly this sounds from people who are comfortable using Webpack. Webpack was around before ES6 and some of Webpack's semantics were so useful that Javascript itself adopted them later on. I hope that TC-39 considers adding these semantics to their spec for import in future versions of EMCAscript, because they are very useful features.

Thanks for opening this issue and dealing with me politely, despite my unilateral vitriol on other forums :). Webpack is a great project and I commend all the hard work put into it so far.

**Comment by skipjack** [comment]
Yeah I think a paragraph on this in the __Concepts__ documentation, probably on the [index page](https://webpack.js.org/concepts/) would suffice.

> The specific thing I was unclear about was that Webpack is an extension of the Javascript language itself, IE, a "complier", and not simply a build tool that you can swap out for other build tools like Gulp, Grunt, Browserify, etc.
>
> Specifically, the import extensions for CSS, images, and other static assets are not part of Javascript at all. They're extra features that Webpack adds that will break your source code if you choose to replace Webpack with another "build tool".

Yep, at least from an `import` standpoint it is an extension for JavaScript. Webpack does force you to add a loader for anything besides `js` and `json` so I guess that's why most developers recognize that it's an extension but I think you're right that explicitly stating it would be good.

> This couples the of your application to the by making them all one system. I think this is well-understood by seasoned Webpack developers, but was not well understood by me, a regular Javascript developer who sees "Gulp vs Webpack!" articles everywhere and thought that they were both swap-outtable for each other.

Fair enough.

> The only thing I would suggest changing is making the documentation on this more clear on the main website. If developers knew that they were buying into an alternate version of Javascript when they were installing Webpack, I would be happy that these rather strong trade-offs are adequately communicated.

Does my suggestion about adding something in __Concepts__ sound reasonable. If so, would you be willing to submit a PR?

**Comment by TheLarkInn** [comment]
These are great observations! @skipjack I think there's a great story here
for guides and concepts. Maybe we cover the hot points.
