### ISSUE TITLE
Add guides on using webpack with x

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#1746]
There is a great article that @maecapozzi has written found [here](https://code.likeagirl.io/how-to-set-up-d3-js-with-webpack-and-babel-7bd3f5e20df7) that covers how to use webpack with d3! 

There are some small nits that I'd make that we can address when the PR comes in. This issue can be for: 

* Adding the article!!!
  * I have talked with @maecapozzi who expressed the interest in adding this into `guides`.

* Where should it go?
  * @skipjack I think theres a great opportunity for some content hierarchy around this. Even though the content might be the same, for each "use webpack with x" article, there are small subtleties that are specific optimizations for each library (IE: favoring d3-arch over d3.arch) that we can help educate about the why and build a better foundational context for using webpack the right way. (Or just understanding why you use a technique vs a different one).

**Comment by skipjack** [comment]
Respectfully, I still strongly disagree with doing this as I've mentioned when it's come up before (e.g. #1394). There are still glaring holes in big parts of our documentation like the __API__ section and a lengthy checklist of dev todos that need to get done (see #1525).

On top of that, I really don't see the need for creating more guides to maintain that don't provide too much value. If you've read _Getting Started_, then it's pretty straightforward to extrapolate that information to your library of choice. I think @maecapozzi's article is good as a blog post but if you read through it, it's really only [the end](https://code.likeagirl.io/how-to-set-up-d3-js-with-webpack-and-babel-7bd3f5e20df7#e147) that discusses `d3` and it basically just instructs the reader to `npm install d3`,`import` it, and use it.

As mentioned in #1394, I think it's much better to link out to this content rather than trying to recreate all these guides here. We already have 20+ guides, some of which still need to be pruned  and moved to other parts of the docs. This ticket is basically suggesting that we infinitely extend the number of articles in that section as there are literally hundreds, if not thousands, of popular frameworks out there. At most, I think maybe a listing of links to articles like this for each framework could be created, but even that I think is overkill.

I'm happy to welcome contributors, and maybe even more content, but let's at least try to get our core documentation into a good place before jumping into things like this. I'm closing, but I'll mark it as `reconsider` and I'm happy to continue the discussion either here or offline. If someone, e.g. @maecapozzi, wanted to start a PR to add a listing of per-framework links as mentioned above, kind of like [starter kits](https://webpack.js.org/starter-kits/), I'd be happy to review and possibly merge.
