### ISSUE TITLE
SEO - HTML in Google Search Description

### ISSUE THREAD

**Issue by brutalcrozt** [webpack/webpack.js.org#1748]
quick look: 
![webpack unwanted issue](https://user-images.githubusercontent.com/3001652/34055254-f869ec9e-e200-11e7-9628-63f3788c7b86.png)

i am on learning state, would be more than happy to know how to resolve this one.

**Comment by pierreneter** [comment]
Can I know what keyword you are using?

**Comment by brutalcrozt** [comment]
keyword: webpack.js.org , yeah i see it differ one with the other.

**Comment by skipjack** [comment]
I'm not sure how much we can do about this outside of actually changing the content on that page. The `meta` description tag looks correct:

![image](https://user-images.githubusercontent.com/8988697/34058970-f83f0ce6-e1aa-11e7-8096-6f2d764b9b13.png)

**Comment by skipjack** [comment]
I found a [decent article](https://www.firstscribe.com/google-change-title-description-search-results/) on the topic but I'm realizing why the hits are coming back that way:

![image](https://user-images.githubusercontent.com/8988697/34083512-eac9f602-e33f-11e7-9309-c3401098fa36.png)

It's the `webpack` and `.js` in `webpack.js.org` that it's trying to find hits on (you can see a bunch are bold). I was originally thinking that the problem was the first text on the page contained code blocks but it's really just that the _hits are around the code blocks_. I thought we might be able to add a better description as the initial page text and call it a day but now I don't think that'll fix the issue. I also don't see us removing those code blocks from the page so I'm not sure what else we can do.

Closing, but feel free to continue the discussion or submit a PR if either of you think there might be a better solution.
