### ISSUE TITLE
Issue Docs are Scroll-jacking

### ISSUE THREAD

**Issue by ahmadawais** [webpack/webpack.js.org#1787]
The new site docs are kind of scroll-jacking and it's very hard to read.

Here's a GIF

![image](http://on.ahmda.ws/oojG/c)

Though, it's way worse than how it looks in there.

Peace! ✌️

**Comment by skipjack** [comment]
This is due to the `Sidebar` component's sticky behavior (which was highly requested) and we are aware of it though it is somewhat dependent on browser/os. We're going to switch to something simpler and more performannt like `position: sticky` or a package soon. Feel free to submit a PR to improve it if you don't want to wait, else it should be updated soon but there's a few other things at the top of our priority list atm.
