### ISSUE TITLE
Devs - More complex examples added to upgrade path and configurations

### ISSUE THREAD

**Issue by knittingcodemonkey** [webpack/webpack.js.org#1797]
I would very much like to see more complex examples highlighting how each configuration could be used in the plugins and modules sections. The simple examples do cover a lot of what most people need, but as soon as there is an additional config required, that info becomes very difficult to find.

**Comment by skipjack** [comment]
Holy moly, you went on an issue binge!

> The simple examples do cover a lot of what most people need, but as soon as there is an additional config required, that info becomes very difficult to find.

This is kind of the point. Our _Guides_ section does a fair amount of hand-holding through the core features but then the idea is to point users to next steps and relevant reference-like docs for users to dig deeper. Webpack's API is far too broad and far-reaching for us to maintain highly detailed examples for every feature. We already have 20+ guides and those take time to maintain and keep up to date (plus we're trying to clean up the other sections).

If you notice that particular features are undocumented, please feel free to submit a PR that adds the missing bits. Or if you feel a section is written poorly or could use one more example, please submit a change to resolve it. __However__, please note that we don't have plans to significantly expand the __Guides__ section of the site or add guide-like diffs throughout the rest of the site. Much of the rest of the site (e.g. _API_, _Configuration_, _Plugins_, and _Loaders_) is all intended to be reference-like documentation.

Note that we are still working on some of the sections that are still somewhat unorganized and imcomplete (i.e. _API_). See #1754 and the `next` branch for more on where we plan to take things when webpack v4 is released.

As it stands right now, this issue is way too broad to be actionable -- and I'm not sure what your requesting is the direction we want to take the site. Feel free to continue the discussion but I'm closing as I don't think we can address this.

**Comment by knittingcodemonkey** [comment]
I did go on a bit of an issue binge. I can see your point with this item being too broad to be actionable. I feel that my specific concern could have been handled as part of the upgrade paths section requested in a different issue. Thank you for spending the time to explain.
