### ISSUE TITLE
Config - Document `splitChunks` and `minimize`

### ISSUE THREAD

**Issue by kingdaro** [webpack/webpack.js.org#1812]
For https://github.com/webpack/webpack/pull/6416: include links to `config.optimize.splitChunks` and `config.optimize.minimize` when the relevant docs are merged.

**Comment by skipjack** [comment]
Can you submit a PR directed at the `next` branch to resolve this? BTW, the other v4 changes are tracked in #1706 so I may add this as a comment there. We won't merge `next` into `master` until v4 is actually released, otherwise we'd get a bunch of reports of missing features. But, if you submit the PR to `next`, these docs would be there as soon as it is merged. You could even link directly to the `next` branch in the meantime.

cc @TheLarkInn

**Comment by jeremenichelli** [comment]
@kingdaro are you working on this? If not I can take care of it :)

**Comment by kingdaro** [comment]
@jeremenichelli Go for it, I'm busy.

**Comment by jeremenichelli** [comment]
Here's the PR for it: https://github.com/webpack/webpack.js.org/pull/1863

**Comment by jeremenichelli** [comment]
Closing since we have an issue for optimization section and we already merged splitChunks docs.
