### ISSUE TITLE
Translation - Filipino Contribution

### ISSUE THREAD

**Issue by vinzruzell** [webpack/webpack.js.org#1826]
I would like to contribute Filipino translation thru github as per utopian rule.

**Comment by skipjack** [comment]
@vinzruzell that would be fantastic. We don't officially support translation at the main repo yet however #295 exists to discuss that. I've never heard of Utopian before but it looks interesting so I'm making an account to check it out. You may want to suggest that on the other thread and see what others think. _If it's free for open source_ and more mature than GitLocalize, it may be a good option for us. Our primary concern is separate PR and issue management so, if it allows those things and just modifies a `/locales` directory, maybe it would be a good fit.

For now... I would recommend you fork the repo, and start translating content. You may want to begin with the `next` branch since that represents the upcoming `v4` docs which will be out in the next month or two (it seems). The other translation forks, i.e. the korean and chinese versions, are hosted separately from this site (but we can add a link to them in our language dropdown). I would recommend talking to the other i18n folks, specifically @dear-lizhihua, @lcxfs1991, and @Lutece.

Closing, but feel free to continue the conversation here or on #295.
