### ISSUE TITLE
Contribute - Google Summer of Code Page

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack.js.org#1849]
- [x] Check the current issues to ensure you aren't creating a duplicate.
- [x] Consider making small typo fixes and such directly as pull requests.
- [x] For the voting application, go to https://github.com/webpack-contrib/voting-app.
- [x] For loader/plugin docs, consider opening an issue in the corresponding repository.
- [x] No existing issue? Go ahead and open a new one.

Webpack is participating in Google Summer of Code. It would be nice to create a page at webpack.js.org with the proposals from this [page](https://docs.google.com/document/d/17snmViHEAM3vhj6bf0nH0-i0so_rQf4PeK5OuCrXcV8/edit)

**Comment by skipjack** [comment]
@ev1stensberg that page looks pretty well thought out so whenever you think it's pretty much ready to go just submit a PR to add it to the __Contribute__ section (`/src/contribute`) of the site. Then I would recommend treating that page as the source of truth for it (instead of the google doc) and you/others can submit more PRs as things change.
