### ISSUE TITLE
How to - Upgrade from webpack 1

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#20]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/how-to/upgrade-from-webpack-1.md).

- [ ] include changes to the resolver
- [ ] babel/treeshaking
- [ ] ...

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by logaretm** [comment]
I guess we can start by pointing out that babel's transform CommonJS should not be used with *tree shaking* since Webpack can handle it now. This preset [babel-preset-es2015-webpack](https://github.com/gajus/babel-preset-es2015-webpack) makes it easier to install dependencies instead of "babel-preset-es2015".

having said that, maybe we could structure the chapter into features, and what does it take to get it to work when migrating and possible gotchas.

I'm looking at this [gist](https://gist.github.com/sokra/27b24881210b56bbaff7) and I think its a very good starting point.

**Comment by bebraw** [comment]
Yeah, that sounds good.

> having said that, maybe we could structure the chapter into features, and what does it take to get it to work when migrating and possible gotchas.

I have specific how-tos and conceptual discussion at my PR (#39) so that sort of info would fit there.

**Comment by bebraw** [comment]
Done. Closing.
