### ISSUE TITLE
Delete logs from code snippets

### ISSUE THREAD

**Issue by jeremenichelli** [webpack/webpack.js.org#2117]
As discussed in this PR https://github.com/webpack/webpack.js.org/pull/2115, we should eliminate logs from code snippets (unless they provide some specific feedback related to the current article) because they are super hard to keep up to date as the core changes.

**Comment by montogeek** [comment]
The reason I brought this issue is because an user could see an example using webpack 3.2 and the next link example would use webpack 4.5, this will confuse the user a lot.

I would say that all examples should work with the latest stable webpack version.

We also have to take into account docs versioning.

**Comment by jeremenichelli** [comment]
That's true @montogeek, we could also turn this issue into _Update all logs to 4.x.x_, I'm fine with both.

**Comment by jeffin143** [comment]
@montogeek , solved in 2574 let's close this :)
