### ISSUE TITLE
Backers design

### ISSUE THREAD

**Issue by montogeek** [webpack/webpack.js.org#259]
Hi!

Currently splash page shows backers list, like this:
![screen shot 2016-10-17 at 16 50 25](https://cloud.githubusercontent.com/assets/1002461/19456998/e87c5bb6-9489-11e6-8ea3-39c745a1f20a.png)

I checked Splash design https://github.com/skipjack/webpack-design/blob/master/Splash.psd, but not found information about how should it look.

I want to help fixing it!

**Comment by skipjack** [comment]
@montogeek yea it definitely needs fixing. The design is pretty outdated at this point so I wouldn't refer to it anymore and the sponsor's section was added recently.

Did you have an idea about how to fix it? I was thinking about trying to wrap them but since it's an svg it's not easy fix. Let me know your thoughts, and check out #260 for the latest splash page design.

**Comment by NejcZdovc** [comment]
@skipjack I think this can be closed.
