### ISSUE TITLE
Organization page table looks broken

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#280]
The [organization](https://webpack.js.org/organization/) page is a bit broken:

![webpack](https://cloud.githubusercontent.com/assets/533616/19729706/3639cc16-9b98-11e6-89ba-0f241a02d456.png)

**Comment by NejcZdovc** [comment]
The only solution without changing tables completely is to set fixed width of the cells.

I personally would change this to card layout. We don't need a table here. We just need to display all projects. This can be easily solved by different layout.

http://thenextweb.com/wp-content/blogs.dir/1/files/2015/06/Screen-Shot-2015-06-16-at-08.57.56.png

https://material.google.com/components/cards.html

**Comment by SpaceK33z** [comment]
Using cards is fine with me, but is there no way to fix it so that it uses the minimum width available?

**Comment by skipjack** [comment]
I just pushed fa8c6616e which contains a fix for this. The issue was a `max-width` declaration on all images.

I agree with @NejcZdovc that we should consider using something other than a table to lay this out. This relates to our discussion in #246.

Maybe a custom `Stats` component and an `organizations.json` sheet would make the most sense for this. It could map the data to cards, a table, or whatever else... I'm willing to open a PR to experiment with this idea. This would mean moving the custom logic for the `stats` language from our `markdown.js` utility, which is already a bit cluttered, to the new component.

**Comment by bebraw** [comment]
Moving the logic could be a good idea. 👍

**Comment by skipjack** [comment]
This is fixed for now although I know tables still aren't perfect. Let's move this conversation back over to #246.
