### ISSUE TITLE
Search unicode doesn't render on windows

### ISSUE THREAD

**Issue by dwelle** [webpack/webpack.js.org#345]
Search button unicode symbol on main page isn't rendered correctly on Windows 7, chrome 54 (not on default `Western (Windows1252)`, nor `Unicode (UTF-8)` encoding).

![image](https://cloud.githubusercontent.com/assets/5153846/20381902/d5e68dd6-aca9-11e6-9169-f8f631467286.png)

**Comment by skipjack** [comment]
@dwelle thanks for pointing this out!

Any one have an idea of what we can do to fix this? I chose to use the unicode glyph over an icon from our icon-font (which I'm about to update) because @bebraw and I had discussed decoupling some of these components into their own repos. However we could always use the icon font for the time being and just extract the necessary svg if we ever make that move.

**Comment by SpaceK33z** [comment]
@skipjack agree with you, probably best to extract when we make that move.

**Comment by skipjack** [comment]
Ok I'm about to try to introduce the fontgen-loader so I'll address this there as well.
