### ISSUE TITLE
Incorrect default value for `resolve.extensions`

### ISSUE THREAD

**Issue by glen-84** [webpack/webpack.js.org#4805]
Refer to [this](https://github.com/webpack/webpack.js.org/issues/4805#issuecomment-812486496) comment.

---

## Feature request

Allow `"..."` to be used in `resolve.extensions` to extend the default values.

**What is the expected behavior?**

```js
resolve: {
    extensions: ["...", ".ts", ".vue"] // Allow this.
}
```

**What is motivation or use case for adding/changing the behavior?**

Extend the defaults without having to redefine them.

**How should this be implemented in your opinion?**

Similar to how it's implemented in other places, I assume.

**Are you willing to work on this yourself?**

Not in the short term.

**Comment by glen-84** [comment]
Ya, this is a problem in Vuetify that I reported [here](https://github.com/vuetifyjs/vue-cli-plugins/pull/247#issuecomment-810130711). I'll create a separate issue for it soon.

**Comment by chenxsan** [comment]
`'...'` does work as expected in my test, here's an example https://codesandbox.io/s/webpack-forked-13d1z?file=/webpack.config.js.

Notice that we should inspect `resolve.byDependency` instead of `resolve.extensions` for the default value, the latter defaults to `[]`, i.e., that default value listed in documentation for [`resolve.extensions`](https://webpack.js.org/configuration/resolve/#resolveextensions) is wrong.

**Comment by glen-84** [comment]
@chenxsan,

Yes, it does work. I thought that it wasn't working because `.mjs` was not being included, but it was the documentation that was incorrect (hence this issue).
