### ISSUE TITLE
Development - Add Class Hierarchy

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#487]
Here's a pic to add from @TheLarkInn:

![webpack_2_-_uml](https://cloud.githubusercontent.com/assets/166921/21108395/a3d4bef0-c09d-11e6-852f-5ef881559e5e.png)

**Comment by skipjack** [comment]
I can pick this up... @bebraw maybe we can just start by adding this to the `development/index.md` guide? I can add a little lead in paragraph to give some context.

**Comment by bebraw** [comment]
@skipjack Yup, that would be a start. The problem is that I don't know if it's entirely truthful image anymore. You would have to ask Tobias about that.

**Comment by skipjack** [comment]
@bebraw let's just hold off on this until #469 is in the works, especially since we need clarification on if this illustration still applies. I referenced this over there so it can always be re-opened when that is started or sooner if we can get an idea of whether it still applies or if it needs updating.
