### ISSUE TITLE
css-loader documentation has a mistake: local value should use :local

### ISSUE THREAD

**Issue by summer-wu** [webpack/webpack.js.org#5262]
![image](https://user-images.githubusercontent.com/2476434/128301569-3703e9df-6148-4546-91af-a20864e76ae1.png)
Should be `:local`

**Comment by chenxsan** [comment]
Not really a mistake in my opinion. But it might be more suitable to use a normal "local" instead of one wrapped in `<code></code>`.

E.g.,

> Using local value requires you to specify `:global` classes. Using global value requires you to specify `:local` classes.

Anyway, You can file an issue over https://github.com/webpack-contrib/css-loader to see if they're willing to update. Since we're reading source from its readme, there's nothing can be done in this repository.
