### ISSUE TITLE
Question about cache option

### ISSUE THREAD

**Issue by aamir-mns** [webpack/webpack.js.org#5283]
**Feature to document**
cache https://github.com/webpack/webpack.js.org/blob/master/src/content/configuration/cache.mdx

**Author(s)**

**Additional information**
Sorry not sure if this is a good place to ask the question. I am using the cache option with `type: 'filesystem',` but is there a way to exclude a folder in node_modules (regex or namespace e.g. @my-componay/folders)?
Something like
```js
cache: {
  type: 'filesystem',
  exclude: /node_modules\/(?!(@mands)\/).*/,
}
```

Also, I am assuming if I update an npm package, it should invalidate the cache.

[ ] I am willing to work on this issue and submit a pull request.

**Comment by alexander-akait** [comment]
No way, it is impossible, otherwise cache will be broken, if something will be changed and your build depend on it, please use https://webpack.js.org/configuration/cache/#cachebuilddependencies, also you can use https://webpack.js.org/configuration/cache/#cachemanagedpaths and remove `node_modules` if you need to do file snapshots (i.e. timestamp/hashing of content), feel free to feedback
