### ISSUE TITLE
npx doesn't work with `webpack`

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack.js.org#5477]
**Feature to document**

We need to change `npx webpack build` to `npx webpack-cli build` (for other commands too).

Places - https://webpack.js.org/api/cli/ + all package where we use `npx`.

Why? When you run `npx webpack build`, npm install `webpack` in temporary directory, inside `webpack` we ask to install `webpack-cli` and if developer ask `yes`, we run `npm i -D webpack-cli`, but `webpack-cli` will be installed in `node_modules` inside package, not in npx temporary directory, so `webpack` can't never found (i.e. `require()`/`import()`) `webpack-cli`.

Shorty:
- if you you have `webpack` and `webpack-cli` in your `package` and install them you can use `npx webpack build`
- otherwise command will not work

/cc @chenxsan @snitin315 I think high priority for docs

Simple reproducible example:
1. Create a new project
2. Create `src/index.js` with any content
3. Run `npx webpack build`

**Author(s)**

Any

**Additional information**

[ ] I am willing to work on this issue and submit a pull request.

**Comment by anshumanv** [comment]
Fix here - #5478

**Comment by chenxsan** [comment]
1. When we use 'npx webpack' in our document, we're actually meaning 'node_modules/.bin/webpack'. The former is used only because it's shorter than latter, not because it covers both cases when webpack is either installed or not. If it's causing problems now, we can use the latter explicitly so users would know that they should install the packages first.
2. Generally i don't think it's a good idea to use 'npx webpack-cli' instead everywhere, it might cause new confusion like why they update 'npx webpack' command to 'npx webpack-cli' now? Some breaking changes I don't know? Not to mention 'webpack' is much easier to type than 'webpack-cli'.

**Comment by alexander-akait** [comment]
@chenxsan Okay, sounds reasonable, let's add note about that developer should install `webpack-cli` to use `webpack` as command and do not rely on `npx` behaviour

**Comment by anshumanv** [comment]
What would be the apt place for the note? I'll modify the PR to revert to the original command and add a note instead.

**Comment by chenxsan** [comment]
@anshumanv How about the cli page https://webpack.js.org/api/cli/? I think it could be the most relevant page.

**Comment by anshumanv** [comment]
Yeah CLI page sounds good, let me add the note there :+1:
