### ISSUE TITLE
Whats New In Webpack 2 - Resolvers

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#68]
This will be a sub issue, under "Whats New in Webpack 2"

**Comment by TheLarkInn** [comment]
We can stub this out. In a "Whats New in Webpack2" folder? Any opinions on this? @bebraw

**Comment by bebraw** [comment]
Maybe start with a section at #20 given that's a priority item. If it looks like the ideas can be split into separate articles, then we'll split.

**Comment by TheLarkInn** [comment]
Perfect I like. Absolutely.

**Comment by sebastiandeutsch** [comment]
# Webpack 2.0 Resolving

Webpack 2.0 has an updated enhanced resolving mechanism:

```
resolve: {
  extensions: ['', '.js', '.jsx'],
  modules: ['src', 'node_modules'],
  plugins: [new DirectoryNamedWebpackPlugin()]
  ...
},
```

This is a complete list of all possible fields within `resolve`:

| Field                    | Default                     | Description                                                                        |
| ------------------------ | --------------------------- | ---------------------------------------------------------------------------------- |
| modules                  | ["node_modules"]            | A list of directories to resolve modules from, can be absolute path or folder name |
| descriptionFiles         | ["package.json"]            | A list of description files to read from |
| plugins                  | []                          | A list of additional resolve plugins which should be applied |
| mainFields               | ["main"]                    | A list of main fields in description files |
| aliasFields              | []                          | A list of alias fields in description files |
| mainFiles                | ["index"]                   | A list of main files in directories |
| extensions               | [".js", ".json", ".node"]   | A list of extensions which should be tried for files |
| enforceExtension         | false                       | Enforce that a extension from extensions must be used |
| moduleExtensions         | []                          | A list of module extsions which should be tried for modules |
| enforceModuleExtension   | false                       | Enforce that a extension from moduleExtensions must be used |
| alias                    | []                          | A list of module alias configurations or an object which maps key to value |
| resolveToContext         | false                       | Resolve to a context instead of a file |
| unsafeCache              | false                       | Use this cache object to unsafely cache the successful requests |
| cachePredicate           | function() { return true }; | A function which decides wheter a request should be cached or not. An object is passed to the function with `path` and `request` properties. |
| fileSystem               |                             | The file system which should be used |
| resolver                 | undefined                   | A prepared Resolver to which the plugins are attached |

## Upgrade from Webpack 1.x to Webpack 2.x

- `resolve.root` has been removed if you need it add the directory to the `modules` list
- Instead of adding a resolver to `plugins` of your webpack config use the new `resolve.plugin` field

**Comment by bebraw** [comment]
Looks great. 👍

**Comment by sokra** [comment]
The defaults in webpack are different: https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L73-L93

**Comment by sebastiandeutsch** [comment]
Would it make sense to align these defaults in this repo - I could work on this.

**Comment by TheLarkInn** [comment]
Yes I think it would.

**Comment by TheLarkInn** [comment]
@sebastiandeutsch I'd love to see a PR on this. If you aren't already working on it. We can provide some direction if needed.

**Comment by sebastiandeutsch** [comment]
@TheLarkInn You can see it here: https://github.com/webpack/enhanced-resolve/pull/39 I'll update the docs accordingly when it's accepted.

**Comment by sebastiandeutsch** [comment]
# Webpack 2.0 Resolving

Webpack 2.0 has an updated enhanced resolving mechanism:

```
resolve: {
  extensions: ['', '.js', '.jsx'],
  modules: ['src', 'node_modules'],
  plugins: [new DirectoryNamedWebpackPlugin()]
  ...
},
```

This is a complete list of all possible fields within `resolve`:

| Field                    | Default                     | Description                                                                        |
| ------------------------ | --------------------------- | ---------------------------------------------------------------------------------- |
| modules                  | ["node_modules"]            | A list of directories to resolve modules from, can be absolute path or folder name |
| descriptionFiles         | ["package.json"]            | A list of description files to read from |
| plugins                  | []                          | A list of additional resolve plugins which should be applied |
| mainFields               | ["main"]                    | A list of main fields in description files |
| aliasFields              | []                          | A list of alias fields in description files |
| mainFiles                | ["index"]                   | A list of main files in directories |
| extensions               | [".js", ".json"]   | A list of extensions which should be tried for files |
| enforceExtension         | false                       | Enforce that a extension from extensions must be used |
| moduleExtensions         | []                          | A list of module extsions which should be tried for modules |
| enforceModuleExtension   | false                       | Enforce that a extension from moduleExtensions must be used |
| alias                    | []                          | A list of module alias configurations or an object which maps key to value |
| resolveToContext         | false                       | Resolve to a context instead of a file |
| unsafeCache              | true                       | Use this cache object to unsafely cache the successful requests |
| cachePredicate           | function() { return true }; | A function which decides wheter a request should be cached or not. An object is passed to the function with `path` and `request` properties. |
| fileSystem               |                             | The file system which should be used |
| resolver                 | undefined                   | A prepared Resolver to which the plugins are attached |

## Upgrade from Webpack 1.x to Webpack 2.x

- `resolve.root` has been removed if you need it add the directory to the `modules` list
- Instead of adding a resolver to `plugins` of your webpack config use the new `resolve.plugin` field

**Comment by sebastiandeutsch** [comment]
I've updated the defaults as @sokra pointed out.

**Comment by akomm** [comment]
Where does `DirectoryNamedWebpackPlugin` come from? could not find it in source.

**Comment by sebastiandeutsch** [comment]
@akomm it's an example Plugin that can be used.

**Comment by sebastiandeutsch** [comment]
It's not in the source.

**Comment by akomm** [comment]
Okay. I was just looking for a reason, why [this](https://github.com/webpack/webpack/issues/2708#issuecomment-246620893) does not work and thought that the plugin is responsible to provide the descriptionFiles functionality.

**Comment by bebraw** [comment]
Looks like a related PR was merged. Time to close.

**Comment by drac** [comment]
**Correction**

For those who gets the error like below;

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[0] should not be empty.
```

Try not to use `''` (empty string), use `'*'` instead.

example:
```
...
extensions: ['*', '.js', '.jsx'],
...
```

**Comment by sokra** [comment]
@drac no, `*` has not effect other that accepting `module*` as filename... Instead omit the empty string as it's added by default.

**Comment by drac** [comment]
@sokra you are absolutely right, I edited my comment according to yours.
