### ISSUE TITLE
Concepts - Entry points

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#8]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/concepts/entry-points.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

Reference: https://webpack.github.io/docs/multiple-entry-points.html .

**Comment by TheLarkInn** [comment]
@bebraw before I start actively tackling this doc. I was curious, do we want to give the three ways to define the entry points as seen in the stub? 

* Single Entry (`string`)
* Multi-main entry (`string[]`)
* Multi-entry (`{[key string: string|string[]]}`)

Since this document is supposed to help people understand _why_, my opinion is always to use the object syntax, so I'm having a hard time explaining _why_ someone would use the single entry version (since it appears to be just a shorthand or convenience syntax)

**Comment by TheLarkInn** [comment]
I suppose the typedef would look more like:

`entry: string|string[]|{[key: string]: string|string[]}`

**Comment by bebraw** [comment]
I would default to object syntax unless there's some serious handicap I'm not aware of (check with Tobias). Convenience forms can be mentioned at the entry concept docs.

**Comment by bebraw** [comment]
Closing as the related PR was merged.
