### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by aight8** [webpack/webpack.js.org#812]
I like to read more about webpack and how it's internal works.
But because the docs are in heavy development I never know if some new docs are added.
Is there a way to make some notes in a changelog file or so some bigger changes?

**Comment by SpaceK33z** [comment]
You could read the commits? I don't think we'll ever have time to make a changelog for docs...

**Comment by aight8** [comment]
Yeah sure I can read the commits on every repo ;) but okey, I understand it that this would be to much extra work than

**Comment by rouzbeh84** [comment]
Is there a tagging structure or minimum required amount of updates that would involve a full change log? Perhaps chunking issues into block of 10 or so that are tagged as 'major' or 'significant' updates or possible even just a 'last updated' auto block that goes under the title block and for sections that involve `loaders || modules || plugin` with a 'last updated' comparison next to one another? 

For example: 

[css-loader](/plugins/commons-chunk-plugin/)

Latest Updates:

| This Page | [loader](https://www.npmjs.com/package/css-loader) |
|--- |--- | 
| [date] | [date] | 

Although, I do see how this could become quite a mess to maintain but just throwing it out there...

**Comment by skipjack** [comment]
Yea idk about this one, @rouzbeh84 something like that might not be bad but, as @SpaceK33z mentioned, there's a ton of other work to be done that I would say is much higher priority than this. To get "high-level" overview of the most recent stuff going on in the docs I would say options include:

* Watching this repository
* Subscribing to issues that concern some piece of documentation you're waiting on
* Checking the most recent commits

You can also use the github/git history of an individual file such as [this one](https://github.com/webpack/webpack.js.org/commits/master/content/concepts/entry-points.md) to get an idea of what's changed in any particular place. 

Personally, I also wouldn't be opposed to standardizing my commits to this repository and using some tool to auto-generate a changelog but that might be fairly hard to manage as we have many different contributors opening all different kinds of PRs. 

I'm going to close this for now but maybe it's something we can loop back to down the road.
