### ISSUE TITLE
API content not indexed in search

### ISSUE THREAD

**Issue by simon04** [webpack/webpack.js.org#822]
The content below https://webpack.js.org/api/ cannot be found using the on-page-search. Possibly www.algolia.com needs to be configured to index this tree?

**Comment by bebraw** [comment]
@dzello Can you look into this?

**Comment by dzello** [comment]
Yes, will have a look tomorrow

**Comment by dzello** [comment]
@simon04 I do see some of the content is indexed, `pitching loader` returns results in `/api/loaders page` for example. Do you have a few queries that didn't return any results?

**Comment by simon04** [comment]
Ahh, this is a prefix search on the **page title**:
* Searching for "api" does neither return "Loader API" nor "Plugin API"
* Searching for "Loader API" or "Plugin API" returns the corresponding results
* Searching for "cli" does not return "Command Line Interface (CLI)"
* Searching for "command line" returns the result

Interestingly, for **page sections** a substring search is applied:
* "compilation instance" find the section "The Compilation instance" in "Plugin API"

**Comment by dzello** [comment]
Ahh I see. I'll look into this.

**Comment by dzello** [comment]
Fixed with [this commit](https://github.com/algolia/docsearch-configs/commit/1a7c97c7a5a4b9cd59ec5e4faef6bc8862075863) to the webpack DocSearch config. The `min_indexed_level` setting controls whether headers at various levels in the inferred hierarchy should be indexed as their own records and it was set one level too high to provide good results for API, CLI, etc.

**Comment by simon04** [comment]
@dzello, great! Thank you a lot for your investigation and fix.
