### ISSUE TITLE
Table display: rows not aligned

### ISSUE THREAD

**Issue by simon04** [webpack/webpack.js.org#911]
The rows are not aligned. Tested /w latest Firefox, Chrome.

![2017-02-17-195529_1440x900_scrot](https://cloud.githubusercontent.com/assets/782446/23079023/50ae2a58-f54b-11e6-8c90-17cdf0d37bca.png)

**Comment by skipjack** [comment]
@NejcZdovc can you look into this?

**Comment by Dajust** [comment]
Hi @skipjack, @NejcZdovc,

I'm currently looking into this issues and will love to send a PR if I'm allowed. 

### Mobile First

![webpack js org-guides-comparison- iphone 5](https://cloud.githubusercontent.com/assets/8015514/23102177/a3ddadb6-f6a4-11e6-9462-2320d542bbb7.png)

**Issue**: On screen below 400px, the class `table-td-content` and `table-td-title` collides/overlaps. 
Solution:  Since the parent of both classes is` displayed:flex,` instead of `display:block `on both classes, we could simply utilize the flex property on t`able-td-content`, give it a fixed with `flex:0 0 150`, then progressively adjust the `flex-grow` to 40%. This will prevent them from ever overlapping, even on a screen below 320px, at the same time shrink/grow as needed.
### Desktop
The major course of the dis-aligned table appears to be the <code> element inside each table-td-content. Since the` <code>` is rightly styled `white-space:nowrap`, it forces the `table-td-content` to grow beyond its width.
To fix this, we must first turn off the flex property, then, give all `table-td-content` fixed width. Then set the `overflow-x` to auto. This is the image of how it looks like after edit.
![table-layout-fix-2](https://cloud.githubusercontent.com/assets/8015514/23102130/a5b2c9c4-f6a3-11e6-9bec-3ce9d57daae0.png)

![table-layout-fix](https://cloud.githubusercontent.com/assets/8015514/23102135/ca7bb5d6-f6a3-11e6-83b6-a864d5836295.png)

Note we can further customize the scroll-bar for chrome users :stuck_out_tongue_winking_eye:

**Comment by NejcZdovc** [comment]
@Dajust I am already working on some fixes, so let me finish it first and let's talk afterwords.
