### ISSUE TITLE
Add the ability to auto generate recognition information at the bottom of each document. 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#95]
As a docs maintainer, I would like to incentivize people to write more documentation via public recognition on the documents they author. 

This would probably be done through a script that finds which users have 'contributed' towards a certain document, and display this near the bottom of the page.

**Comment by bebraw** [comment]
First part towards solving this would be to write a little snippet that digs the information from git history. There's likely a npm package that can do this. I remember using one in the past.

Once you have the information, you can generate a md5 based on email addresses attached to a file commits like this `crypto.createHash('md5').update(email).digest('hex')`. This in turn can be used to generate a gravatar.

To get GitHub linking working, you probably need to perform a lookup against GitHub API. If there's enough API, you can actually skip the first step.

**Comment by skipjack** [comment]
I think this is fixed with our [contributors component](https://github.com/webpack/webpack.js.org/tree/master/components/contributors) and the contributors list at the top of each markdown file. @bebraw closing this for now, but what you described does sound like a better solution instead of manually maintaining the list. Feel free to re-open if you were thinking about tackling this soon.

**Comment by bebraw** [comment]
Yeah, the contributors could be dug automatically later on. I recall Tobias was explicitly against that, though.
